[build]
  command = "npm run build"
  publish = "build"
  
  # Build environment
  [build.environment]
    NODE_VERSION = "18.20.8"
    NPM_VERSION = "10.5.0"
    NPM_CONFIG_AUDIT = "false"
    NPM_CONFIG_FUND = "false"
    NEXT_TELEMETRY_DISABLED = "1"

# Optimize build processing
[build.processing]
  skip_processing = false
  
  [build.processing.css]
    bundle = true
    minify = true
    
  [build.processing.js]
    bundle = true
    minify = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https:;
      connect-src 'self' https://formspree.io;
      frame-src 'self';
      object-src 'none';
      base-uri 'self';
      form-action 'self' https://formspree.io;
    """
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache optimization
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Admin access
[[redirects]]
  from = "/admin-secret-access"
  to = "/#admin"
  status = 302